import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/layout/navbar/Navbar"
import Footer from "../components/layout/footer/Footer"
import Menu from "../components/layout/menu/Menu";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
              <div className="container">
                <div className="wrapper">
                  <Navbar />
                  {children}
                  <Footer />
                </div>
              </div>
      </body>
    </html>
  );
}
